from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional
from enum import Enum

class DeviceStatus(str, Enum):
    ONLINE = "online"
    OFFLINE = "offline"
    ERROR = "error"

class DeviceType(str, Enum):
    METER = "meter"
    BREAKER = "breaker"
    SENSOR = "sensor"

# Create Device
class DeviceCreate(BaseModel):
    # Optional: provided by the Flutter UI or generated by the backend for
    # IoT self-registration when omitted.
    device_id: Optional[str] = None
    # Accept either `device_name` (Flutter) or `name`
    name: Optional[str] = None
    device_name: Optional[str] = None
    location: Optional[str] = None
    device_type: DeviceType = DeviceType.METER
    model: Optional[str] = None
    firmware_version: Optional[str] = None

    @property
    def resolved_name(self) -> str:
        return self.device_name or self.name or self.device_id or "Device"

# Device Response
class DeviceResponse(BaseModel):
    id: str = Field(..., alias="_id")
    device_id: str
    name: str
    location: Optional[str] = None
    device_type: DeviceType
    model: Optional[str] = None
    firmware_version: Optional[str] = None
    is_active: bool
    status: DeviceStatus
    last_heartbeat: Optional[datetime] = None
    specifications: dict
    metadata: dict
    statistics: dict
    created_at: datetime
    updated_at: datetime
    
    class Config:
        populate_by_name = True

# Device Update
class DeviceUpdate(BaseModel):
    name: Optional[str] = None
    location: Optional[str] = None
    device_type: Optional[DeviceType] = None
    model: Optional[str] = None
    firmware_version: Optional[str] = None
    specifications: Optional[dict] = None
    metadata: Optional[dict] = None

# Device List Response
class DeviceListResponse(BaseModel):
    id: str = Field(..., alias="_id")
    device_id: str
    name: str
    location: Optional[str] = None
    device_type: DeviceType
    status: DeviceStatus
    last_heartbeat: Optional[datetime] = None
    created_at: datetime
    
    class Config:
        populate_by_name = True

# Device Status Update
class DeviceStatusUpdate(BaseModel):
    status: DeviceStatus
    last_heartbeat: Optional[datetime] = None
